### ISSUE TITLE
[Request]: Implement Streaming Responses

### ISSUE THREAD

**Issue by ericrallen** [InterwebAlchemy/obsidian-ai-research-assistant#15]
**Is your feature request related to a problem? Please describe.**

Responses take too long to deliver to the UI.

**Describe the solution you'd like**

Now that OpenAI has added streaming support to the [`openai` npm package](https://github.com/openai/openai-node), switch to streaming responses to the UI.

**Comment by yigitkonur** [comment]
There hasn't been any improvement in this repo for the past few months - I hope you haven't lost your motivation. I think what you're doing in this field is truly valuable. I hope you create a way for us to boost your motivation here by allowing us to contribute as sponsors <3

**Comment by ericrallen** [comment]
@yigitkonur I really appreciate the kind words. It’s awesome to know that someone is using and enjoying the stuff I’ve built.

I promise that I haven’t abandoned AI Research Assistant - I still use it almost daily and plan to have some updates ready to release after the next couple of weeks are over.

I still have plans to add streaming responses, but it requires a little more work than just enabling the `stream: true` option because when I started this project there weren’t SDKs for the API, the chat completions endpoint didn’t exist, and there were very few examples of how to handle steaming responses, so the chat logic needs some refactoring to support properly rendering chunks.

It’s been just over a month since [v 1.5.0](https://github.com/InterwebAlchemy/obsidian-ai-research-assistant/releases/tag/1.5.0) - which added the GPT-4 model and hot-swapping models during a conversation - was released.

Since then I’ve taken a much needed vacation, and it’s been a busy time where I’ve had a lot of other work to take care of like:

- building a [demo AI app](https://github.com/DVDAGames/local-tabletop-ai-demo) for a talk for [Prompt Engineering Conference](https://promptengineering.rocks/)
- contributing a few features to [Open Interpreter](https://github.com/KillianLucas/open-interpreter)
- updating [another AI demo](https://github.com/InterwebAlchemy/beat-brain) and it’s corresponding talk for [All Things Open](https://2023.allthingsopen.org/sessions/imagined-dragons-building-an-imagination-powered-music-recommendation-platform/)
- learning Python and how to use Jupyter Notebooks via an [interactive demo](https://github.com/ericrallen/sentiment-analysis-notebook) 

Contributing to Open Interpreter has helped me consider and reprioritize some features for AI Research Assistant, but I’d love to know what my users want and need.

Please feel encouraged to provide suggestions for features as [Issues](https://github.com/InterwebAlchemy/obsidian-ai-research-assistant/issues) or start a [Discussion](https://github.com/InterwebAlchemy/obsidian-ai-research-assistant/discussions) so I know what folks are looking for from AI Research Assistant.

**Comment by yigitkonur** [comment]
Great developments, Eric - I certainly don't underestimate your effort, you're producing excellent work. I can imagine that implementing the stream section wasn't easy - it seems like you've been through a busy period and you're still producing great results. As someone who believes in the future of this project, I wouldn't want you to feel any pressure on yourself, I just want to show my support 🙏

**Comment by ericrallen** [comment]
@yigitkonur Streaming responses from OpenAI _should_ be available in the latest version of AI Research Assistant.
